<template>
    <div>
        <div>
            <img src="" alt="">
            <h2></h2>
            <p></p>
        </div>
        <div>
            <i class="pi pi-whatsapp"></i>
        </div>
        <div>
            <h3></h3>
            <ul>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div>
            <h3></h3>
            <ul>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div>
            <h3></h3>
            <ul>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <hr>
        <div>
            <p></p>
            <div>
                <p></p>
                <p></p>
                <p></p>
            </div>
        </div>
    </div>
</template>